language: ruby
install:
  # Install Jekyll and dependencies
  - bundle install --path vendor/bundle
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: "lsxam7lcoh66NNwjGo4KT+Kvznr5bQ/wSmNmCFglJ4CCoXZOJKQ1GKPul9H1/tbMqqO/I6HnIADlon1KMJGka/z44xaaEvSheIj6C6bhXk7Muxjj375UHwitT3MwvoY06Gmr141l9yfkpgBHeEkC35YYjmp+WpwbQymbTD0M4Ac="
branches:
  only:
    - master
